### ISSUE TITLE
fontStyle not working

### ISSUE THREAD

**Issue by xapple** [bcomnes/LaTeX-Font-Settings.tmbundle#1]
I added a `fontStyle` directive to the subsection setting, but it doesn't take effect. Any idea why ?

![screen shot 2013-07-11 at 15 36 39](https://f.cloud.github.com/assets/649288/781857/fb45ee1e-ea2e-11e2-81e6-90f31241b0da.png)

**Comment by sanssecours** [comment]
Hi,

> Hey, thanks for the tip. But unforutnately it didn't seem to have an effect : (

Lucas, you need to add single quotation marks around `'1'` to make it work:

![bundle editor](https://cloud.githubusercontent.com/assets/691989/7844917/c0c974f8-04b3-11e5-97de-047740bb95da.png)
![textmate](https://cloud.githubusercontent.com/assets/691989/7844918/c146f8a6-04b3-11e5-9578-4cb987323079.png)

Kind regards,
  René

**Comment by xapple** [comment]
Yup I got it working thanks !
