### ISSUE TITLE
Increase the number of selection scopes

### ISSUE THREAD

**Issue by wizpig** [bcomnes/LaTeX-Font-Settings.tmbundle#2]
Hey Bret,

I have here a few documents where the author wasn't using \section, \subsection, etc. but instead \begin{section}, \begin{subsection}, etc. 
Unfortunately your package does not recognize this kind of sectioning.
Do you know how I can extend your bundle to recognize them?

Cheers
Alex

**Comment by bcomnes** [comment]
These are all in I think.
