### ISSUE TITLE
separate formatting for text within a footnote

### ISSUE THREAD

**Issue by amroberts1** [bcomnes/LaTeX-Font-Settings.tmbundle#5]
(I first [posted](https://github.com/textmate/latex.tmbundle/issues/124) this on the `latex.tmbundle` github page, but as was noted there, perhaps my comment is more appropriate here.)

I use XeLaTeX to write academic history, and so my documents make much use of the `\footnote{...}` command. (In case it is relevant, I should note that in my documents these footnotes often make use of non-Latin scripts, in particular Greek and Arabic.) It would therefore be a great help to me if the text within footnotes were formatted in TextMate differently from normal text, for example with a smaller font size or a highlighted background. This would make it easier, when looking at a paragraph, to visually distinguish between the main text and footnotes. As a MWE, here is an example paragraph:

```
This sentence makes an argument.\footnote{This footnote substantiates the argument by referencing Author, \emph{Title}, 65.}
This sentence quotes a text in my English translation which reads, ``Know yourself!"\footnote{This footnote contains the quote in the original language: ``\emph{gnōthi seauton}."}
```

(I would usually use `fontspec` in order to print the Greek in a Greek Unicode font -- `\greek{γνῶθι σεαυτόν}` -- but omit that here for simplicity.)

**Comment by bcomnes** [comment]
Yeah! We could probably do something like this. I'll have to see if a selector exists resize on footnote and make it visually smaller or a different highlight.

**Comment by bcomnes** [comment]
I'll ping TextMate people to get that pushed out to everyone.  Cheers!

**Comment by bcomnes** [comment]
Ok Should be out now!

**Comment by amroberts1** [comment]
@bcomnes @sanssecours Great -- thank you very much! I've just had the chance to test it, and it makes a big difference. Two questions about how to tweak the design:

1. Is there an intermediate size between the normal font size and the size now assigned to the `footnote`? The latter now seems a bit on the small side in comparison to the main text.

2. Would there be a way to make the background color for `footnote` more distinct from the normal background color without disrupting the rest of the color scheme? I use the Twilight theme, where the background color isn't very easy to see. When I switch it to themes with a white background, I still find that the light-gray doesn't stand out as much as I would like. (Ideally, the background color for `footnote` would depend on the background color for the theme selected, but I imagine that would be more complicated than a simple tweak.)

**Comment by bcomnes** [comment]
I'll play around with it, but feel freel to make local changes and report back any improvements for darker themes.  Just open the bundle editor, and make some tweaks to the settings that are there.

**Comment by amroberts1** [comment]
Sounds good. Thanks again!
