### ISSUE TITLE
Improve footnote style for dark backgrounds

### ISSUE THREAD

**Issue by bcomnes** [bcomnes/LaTeX-Font-Settings.tmbundle#8]
@amroberts1 made a good observation in https://github.com/bcomnes/LaTeX-Font-Settings.tmbundle/issues/5

> Is there an intermediate size between the normal font size and the size now assigned to the footnote? The latter now seems a bit on the small side in comparison to the main text.
> 
> Would there be a way to make the background color for footnote more distinct from the normal background color without disrupting the rest of the color scheme? I use the Twilight theme, where the background color isn't very easy to see. When I switch it to themes with a white background, I still find that the light-gray doesn't stand out as much as I would like. (Ideally, the background color for footnote would depend on the background color for the theme selected, but I imagine that would be more complicated than a simple tweak.)

Lets use this issue to track progress on this.

**Comment by DOFfactory** [comment]
I am using the command `{ foreground = '#5D87FE'; }` for the scope `meta.footnote.latex`. That's all.
